x-commons: &commons
  networks: [ internal ]
  env_file: .env
  volumes :
    - ".:/app"
    - "./tests/Unit/sandbox:/tmp"

networks :
  internal:

services :
  composer    :
    <<     : *commons
    image  : composer:2
    command: install
  sftp        :
    image   : jmcombs/sftp
    <<      : *commons
    networks: [ internal ]
    ports   : [ "22:22" ]
    command : sftp:sftp:::upload
  s3          :
    image   : quay.io/minio/minio:latest
    <<      : *commons
    networks: [ internal ]
    ports   : [ "9000:9000" ]
    command : server /data
  ftp         :
    <<      : *commons
    image   : garethflowers/ftp-server
    ports   : [ "21:21" ]
    networks: [ internal ]
  test_local  :
    <<     : *commons
    build  : tests/Unit
    command: phpunit ./tests/Unit/LocalProviderTest.php
  test_dropbox:
    <<     : *commons
    build  : tests/Unit
    command: phpunit ./tests/Unit/DropboxProviderTest.php
  test_mega   :
    <<     : *commons
    build  : tests/Unit
    command: phpunit ./tests/Unit/MegaProviderTest.php
  test_gdrive :
    <<     : *commons
    build  : tests/Unit
    command: phpunit ./tests/Unit/GDriveProviderTest.php
  test_sftp   :
    <<        : *commons
    build     : tests/Unit
    command   : phpunit ./tests/Unit/SFtpProviderTest.php
    depends_on: [ sftp ]
  test_ftp    :
    <<        : *commons
    build     : tests/Unit
    command   : phpunit ./tests/Unit/FtpProviderTest.php
    depends_on: [ ftp ]
  test_s3     :
    <<        : *commons
    build     : tests/Unit
    command   : phpunit ./tests/Unit/S3ProviderTest.php
    depends_on: [ s3 ]
  test_sftp_to_s3:
    <<        : *commons
    build     : tests/Unit
    command   : phpunit ./tests/Unit/FromSftpToS3ProviderTest.php
    depends_on: [ sftp, s3 ]
  test_s3_to_local:
    <<        : *commons
    build     : tests/Unit
    command   : phpunit ./tests/Unit/FromS3ToLocalProviderTest.php
    depends_on: [ s3 ]
  test_s3_to_sftp:
    <<        : *commons
    build     : tests/Unit
    command   : phpunit ./tests/Unit/FromS3ToSftpProviderTest.php
    depends_on: [ s3, sftp ]
  test_local_to_s3:
    <<        : *commons
    build     : tests/Unit
    command   : phpunit ./tests/Unit/FromLocalToS3ProviderTest.php
    depends_on: [ s3 ]
